const photos=[
    {
      src:"hotel_img.jpg",
      key:"1",
      id:"1"
    },
    {
      src:"hotel_img.jpg",
      key:"2",
      id:"2"
    },
    {
      src:"hotel_img.jpg",
      key:"3",
      id:"3"
    },
    {
      src:"hotel_img.jpg",
      key:"4",
      id:"4"
    },
    {
      src:"hotel_img.jpg",
      key:"5",
      id:"5"
    },
    {
      src:"hotel_img.jpg",
      key:"6",
      id:"6"
    },
    {
      src:"hotel_img.jpg",
      key:"7",
      id:"7"
    },
    {
      src:"hotel_img.jpg",
      key:"8",
      id:"8"
    }
  ];

export default photos;